# GROUP MEMBERS
**NAME:**<br>
1) IMAN ABADI BIN MOHD NIZWAN - <i>A23CS0084</i> <br>
2) MOHAMED ALIF FATHI BIN ABDUL LATIF - <i>A23CS0112</i> <br>
3) MUHAMMAD AFIQ DANIAL BIN ROZAIDIE - <i>A23CS0117</i>

<h2><u>Dataset Introduction</u></h2>

The main data that we used in this project are cars_2025.csv and FuelCosumption.csv.
The FuelConsumption.csv dataset contain an attributes of a vehicle, including MODELYEAR, MAKE, MODEL, VEHICLECLASS, ENGINESIZE, CYLINDERS, TRANSMISSION, FUELTYPE, as well as multiple fuel consumption metrics such as FUELCONSUMPTION_CITY, FUELCONSUMPTION_HWY, FUELCONSUMPTION_COMB, FUELCONSUMPTION_COMB_MPG, and CO2EMISSIONS.
On the other hand, cars_2025.csv focus on the vehicle registration information or a model feature like date_reg, type, maker, model, colour, fuel, and state. These dataset will use to combined and analyze to explore the relationship between these datasets on vehicle specifications, fuel consumption, and carbon emissions. This data analytics project aims to analyze real-world vehicle emission data to uncover patterns, identify high-emission vehicle categories, and propose strategies for reducing carbon footprints. We will use Python-based analytics tools to explore fuel consumption trends and emission factors to gain insights into the relationship between vehicle characteristics and environmental impact.

<h2><u>Research Question</u></h2>

- How do different car makes and fuel types, as registered in 2025 across various states, influence average carbon emissions, and what patterns can be uncovered through merging a maker and a model of the cars and analyzing vehicle registration data with technical fuel consumption data?
- How can vehicle attributes and registration data be used to classify or cluster car makes and models by their carbon emissions, and what patterns emerge through summary analytics and visual exploration of the 2025 car market?

<h2><u>Data Cleaning and Preparation</u></h2>

1) Drop duplicates <br>
Duplicate rows were identified and removed from both datasets to ensure that each car record is unique and to prevent skewed analysis results. Duplicated were checked by using df.drop_duplicates(inplace = True) function, to drop the same row infortmation in cars_2025. 

3) Drop biased data / null values <br>
Rows containing missing values or incomplete records were removed to eliminate potential bias and maintain the integrity of the analysis. 'Rakan Niaga' row will be removed from the colums state in cars_2025 due to the biased data that have approximately 80% from the entire row in cars dataset.

4) Rename columns <br>
The 'maker' and 'model' columns in the Cars2025 dataset were renamed as 'MAKER MODEL' by using df.rename() function to ensure consistency with the FuelConsumption dataset for accurate merging.

5) Remove special characters <br>
Special characters were removed from the 'MAKER' and 'MODEL' fields to standardize naming conventions and avoid mismatches during data integration.

6) Mapping <br>
A mapping process or using df.map() function was applied to align and match categorical values, such as maker, model and fuel types between the two datasets to ensure consistency.

7) Merging <br>
The cleaned cars_2025 and FuelConsumption datasets were merged with the help of pandas function (pd.merge()) based on common vehicle attributes, enabling a comprehensive view that combines registration and emission information.

8) Data matching <br>
Post-merge data matching was performed to validate the integrity of the merged dataset, ensuring that records from both sources correctly correspond to the same vehicle entities.

In [ ]:
# Import
import numpy as np
import pandas as pd

df = pd.read_csv('cars_2025.csv')
df2 = pd.read_csv('FuelConsumption.csv')

In [6]:
# Clean data 
df.drop_duplicates(inplace = True)
df.drop(df[df['state'] == 'Rakan Niaga'].index, inplace=True)

In [7]:
# Rename columns and match naming of both dataframe
df.rename(columns={'maker': 'MAKER', 'model':'MODEL','fuel':'fuel_type'}, inplace=True)
df2.rename(columns={'MAKE': 'MAKER'}, inplace=True)
df['MAKER'] = df['MAKER'].str.upper()
df['MAKER'] = df['MAKER'].str.replace(r'\s+', '-', regex=True)
df2['MAKER'] = df2['MAKER'].str.replace(r'\s+', '-', regex=True)

In [8]:
df2['FUELTYPE'].value_counts()

FUELTYPE
X    514
Z    434
E     92
D     27
Name: count, dtype: int64

In [9]:
df['fuel_type'].value_counts()

fuel_type
petrol           15589
greendiesel       2526
electric          1851
hybrid_petrol     1526
diesel            1502
Name: count, dtype: int64

In [10]:
# Mapping
fuel_map = {'Z': 'petrol', 'X': 'petrol', 'D': 'diesel', 'E': 'electric'}
df2['fuel_type'] = df2['FUELTYPE'].map(fuel_map)

# Add hybrid for models with "HYBRID" in name
hybrid_mask = df2['MODEL'].str.contains('HYBRID', na=False)
petrol_mask = df2['FUELTYPE'].isin(['Z', 'X'])
diesel_mask = df2['FUELTYPE'] == 'D'

df2.loc[hybrid_mask & petrol_mask, 'fuel_type'] = 'hybrid_petrol'
df2.loc[hybrid_mask & diesel_mask, 'fuel_type'] = 'hybrid_diesel'

df2.drop('FUELTYPE', axis=1, inplace=True)
df2[['MODEL', 'fuel_type']]

           MODEL      fuel_type
0            ILX         petrol
1            ILX         petrol
2     ILX HYBRID  hybrid_petrol
3        MDX 4WD         petrol
4        RDX AWD         petrol
...          ...            ...
1062    XC60 AWD         petrol
1063    XC60 AWD         petrol
1064    XC70 AWD         petrol
1065    XC70 AWD         petrol
1066    XC90 AWD         petrol

[1067 rows x 2 columns]

In [11]:
df2['fuel_type'].value_counts()

fuel_type
petrol           924
electric          92
diesel            27
hybrid_petrol     24
Name: count, dtype: int64

In [12]:
#Display df1
print(df['MAKER'].value_counts().sort_index())
print()
print(df['MODEL'].value_counts().sort_index())
print()
print(df['fuel_type'].value_counts().sort_index())

MAKER
ACURA               1
ALFA-ROMEO          1
ASTON-MARTIN        7
AUDI               66
BAW                 1
                 ...
WESTSTAR-MAXUS     45
XINNENG             3
XPENG              75
ZEEKR             134
ZXAUTO              1
Name: count, Length: 76, dtype: int64

MODEL
009         125
1 Series     12
2 Series     16
2008         11
296          12
           ...
i8            1
iX           11
iX1          25
iX2          55
iX3           5
Name: count, Length: 378, dtype: int64

fuel_type
diesel            1502
electric          1851
greendiesel       2526
hybrid_petrol     1526
petrol           15589
Name: count, dtype: int64

In [13]:
#Diplay df2
print(df2['MAKER'].value_counts().sort_index())
print()
print(df2['MODEL'].value_counts().sort_index())
print()
print(df2['fuel_type'].value_counts().sort_index())

MAKER
ACURA            12
ASTON-MARTIN      7
AUDI             49
BENTLEY           8
BMW              64
BUICK            16
CADILLAC         32
CHEVROLET        86
CHRYSLER         19
DODGE            39
FIAT             10
FORD             90
GMC              49
HONDA            21
HYUNDAI          24
INFINITI         21
JAGUAR           22
JEEP             31
KIA              33
LAMBORGHINI       3
LAND-ROVER       19
LEXUS            22
LINCOLN          11
MASERATI          6
MAZDA            27
MERCEDES-BENZ    59
MINI             36
MITSUBISHI       16
NISSAN           33
PORSCHE          44
RAM              13
ROLLS-ROYCE       7
SCION             9
SMART             2
SRT               2
SUBARU           23
TOYOTA           49
VOLKSWAGEN       42
VOLVO            11
Name: count, dtype: int64

MODEL
1500 (MDS)         2
1500 4X4 (MDS)     2
1500 4X4 DIESEL    1
1500 4X4 FFV       2
1500 DIESEL        1
                  ..
Z4 sDRIVE35is      1
iQ                 1
tC                 2
xB                 2
xD                 2
Name: count, Length: 663, dtype: int64

fuel_type
diesel            27
electric          92
hybrid_petrol     24
petrol           924
Name: count, dtype: int64

In [14]:
print(df.isnull().sum())
print(df2.isnull().sum())

date_reg     0
type         0
MAKER        0
MODEL        0
colour       0
fuel_type    0
state        0
dtype: int64
MODELYEAR                   0
MAKER                       0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
fuel_type                   0
dtype: int64

In [15]:
df_combine = pd.merge(df2,df, on=['MAKER','fuel_type'], how = 'inner')

In [16]:
df_combine.isnull().sum()

MODELYEAR                   0
MAKER                       0
MODEL_x                     0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
fuel_type                   0
date_reg                    0
type                        0
MODEL_y                     0
colour                      0
state                       0
dtype: int64

In [17]:
df_combine.dropna(inplace=True)

In [18]:
df_combine

,MODELYEAR,MAKER,MODEL_x,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,fuel_type,date_reg,type,MODEL_y,colour,state
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,9.9,6.7,8.5,33,196,petrol,2025-02-03,motokar_pelbagai_utiliti,MDX,white,W.P. Kuala Lumpur
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,11.2,7.7,9.6,29,221,petrol,2025-02-03,motokar_pelbagai_utiliti,MDX,white,W.P. Kuala Lumpur
2,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,12.7,9.1,11.1,25,255,petrol,2025-02-03,motokar_pelbagai_utiliti,MDX,white,W.P. Kuala Lumpur
3,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,12.1,8.7,10.6,27,244,petrol,2025-02-03,motokar_pelbagai_utiliti,MDX,white,W.P. Kuala Lumpur
4,2014,ACURA,RLX,MID-SIZE,3.5,6,AS6,11.9,7.7,10.0,28,230,petrol,2025-02-03,motokar_pelbagai_utiliti,MDX,white,W.P. Kuala Lumpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385096,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,12.9,9.3,11.3,25,260,petrol,2025-03-27,motokar,S60,white,W.P. Kuala Lumpur
385097,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,12.9,9.3,11.3,25,260,petrol,2025-04-08,jip,XC40,white,Selangor
385098,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,14.9,10.2,12.8,22,294,petrol,2025-01-10,motokar,S60,silver,Perak
385099,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,14.9,10.2,12.8,22,294,petrol,2025-03-27,motokar,S60,white,W.P. Kuala Lumpur
385100,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,14.9,10.2,12.8,22,294,petrol,2025-04-08,jip,XC40,white,Selangor

In [19]:
df_combine[['MAKER', 'MODEL_y', 'MODEL_x', 'fuel_type']]

        MAKER MODEL_y   MODEL_x fuel_type
0       ACURA     MDX       ILX    petrol
1       ACURA     MDX       ILX    petrol
2       ACURA     MDX   MDX 4WD    petrol
3       ACURA     MDX   RDX AWD    petrol
4       ACURA     MDX       RLX    petrol
...       ...     ...       ...       ...
385096  VOLVO     S60  XC70 AWD    petrol
385097  VOLVO    XC40  XC70 AWD    petrol
385098  VOLVO     S60  XC90 AWD    petrol
385099  VOLVO     S60  XC90 AWD    petrol
385100  VOLVO    XC40  XC90 AWD    petrol

[385101 rows x 4 columns]

In [20]:
# Normalize model
df_combine['MODEL_x_norm'] = df_combine['MODEL_x'].str.lower().str.strip()
df_combine['MODEL_y_norm'] = df_combine['MODEL_y'].str.lower().str.strip()

df_combine['MODEL_MATCHED'] = ''

# Match rows MODEL_y and MODEL_x and create a new column MODEL_MATCHED
for i in range(len(df_combine)):
    if pd.notna(df_combine.loc[i, 'MODEL_y_norm']) and df_combine.loc[i, 'MODEL_y_norm'] in df_combine.loc[i, 'MODEL_x_norm']:
        df_combine.loc[i, 'MODEL_MATCHED'] = df_combine.loc[i, 'MODEL_y']

df_combine[['MODEL_x', 'MODEL_y', 'MODEL_MATCHED']]

         MODEL_x MODEL_y MODEL_MATCHED
0            ILX     MDX
1            ILX     MDX
2        MDX 4WD     MDX           MDX
3        RDX AWD     MDX
4            RLX     MDX
...          ...     ...           ...
385096  XC70 AWD     S60
385097  XC70 AWD    XC40
385098  XC90 AWD     S60
385099  XC90 AWD     S60
385100  XC90 AWD    XC40

[385101 rows x 3 columns]

In [21]:
df_combine.isnull().sum()

MODELYEAR                   0
MAKER                       0
MODEL_x                     0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
fuel_type                   0
date_reg                    0
type                        0
MODEL_y                     0
colour                      0
state                       0
MODEL_x_norm                0
MODEL_y_norm                0
MODEL_MATCHED               0
dtype: int64

In [22]:
df_combine['MODEL_MATCHED'].value_counts()

MODEL_MATCHED
                371599
Cooper            2340
Civic             1572
RX                1239
911 Carrera       1008
                 ...
Quattroporte         2
Vanquish             1
MDX                  1
Mulsanne             1
RS7                  1
Name: count, Length: 86, dtype: int64

In [23]:
#Drop rows where MODEL_MATCHED is empty
df_combine.drop(df_combine[df_combine['MODEL_MATCHED'] == ''].index, inplace=True)

In [24]:
df_combine

,MODELYEAR,MAKER,MODEL_x,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,...,CO2EMISSIONS,fuel_type,date_reg,type,MODEL_y,colour,state,MODEL_x_norm,MODEL_y_norm,MODEL_MATCHED
2,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,12.7,9.1,11.1,...,255,petrol,2025-02-03,motokar_pelbagai_utiliti,MDX,white,W.P. Kuala Lumpur,mdx 4wd,mdx,MDX
25,2014,ASTON-MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,17.4,11.3,14.7,...,338,petrol,2025-01-07,motokar,Vantage,orange,W.P. Kuala Lumpur,v8 vantage,vantage,Vantage
32,2014,ASTON-MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,18.1,12.2,15.4,...,354,petrol,2025-01-07,motokar,Vantage,orange,W.P. Kuala Lumpur,v8 vantage,vantage,Vantage
39,2014,ASTON-MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,17.4,11.3,14.7,...,338,petrol,2025-01-07,motokar,Vantage,orange,W.P. Kuala Lumpur,v8 vantage s,vantage,Vantage
46,2014,ASTON-MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,M6,18.1,12.2,15.4,...,354,petrol,2025-01-07,motokar,Vantage,orange,W.P. Kuala Lumpur,v8 vantage s,vantage,Vantage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385069,2014,VOLVO,S60,COMPACT,2.5,5,AS6,11.3,7.8,9.7,...,223,petrol,2025-03-27,motokar,S60,white,W.P. Kuala Lumpur,s60,s60,S60
385071,2014,VOLVO,S60 AWD,COMPACT,2.5,5,AS6,11.6,8.3,10.1,...,232,petrol,2025-01-10,motokar,S60,silver,Perak,s60 awd,s60,S60
385072,2014,VOLVO,S60 AWD,COMPACT,2.5,5,AS6,11.6,8.3,10.1,...,232,petrol,2025-03-27,motokar,S60,white,W.P. Kuala Lumpur,s60 awd,s60,S60
385074,2014,VOLVO,S60 AWD,COMPACT,3.0,6,AS6,13.2,9.5,11.5,...,264,petrol,2025-01-10,motokar,S60,silver,Perak,s60 awd,s60,S60
385075,2014,VOLVO,S60 AWD,COMPACT,3.0,6,AS6,13.2,9.5,11.5,...,264,petrol,2025-03-27,motokar,S60,white,W.P. Kuala Lumpur,s60 awd,s60,S60

In [25]:
df_combine.reset_index(inplace = True)

In [26]:
df_combine.drop(['index'], inplace = True ,axis = 1)

In [27]:
df_combine

,MODELYEAR,MAKER,MODEL_x,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,...,CO2EMISSIONS,fuel_type,date_reg,type,MODEL_y,colour,state,MODEL_x_norm,MODEL_y_norm,MODEL_MATCHED
0,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,12.7,9.1,11.1,...,255,petrol,2025-02-03,motokar_pelbagai_utiliti,MDX,white,W.P. Kuala Lumpur,mdx 4wd,mdx,MDX
1,2014,ASTON-MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,17.4,11.3,14.7,...,338,petrol,2025-01-07,motokar,Vantage,orange,W.P. Kuala Lumpur,v8 vantage,vantage,Vantage
2,2014,ASTON-MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,18.1,12.2,15.4,...,354,petrol,2025-01-07,motokar,Vantage,orange,W.P. Kuala Lumpur,v8 vantage,vantage,Vantage
3,2014,ASTON-MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,17.4,11.3,14.7,...,338,petrol,2025-01-07,motokar,Vantage,orange,W.P. Kuala Lumpur,v8 vantage s,vantage,Vantage
4,2014,ASTON-MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,M6,18.1,12.2,15.4,...,354,petrol,2025-01-07,motokar,Vantage,orange,W.P. Kuala Lumpur,v8 vantage s,vantage,Vantage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13497,2014,VOLVO,S60,COMPACT,2.5,5,AS6,11.3,7.8,9.7,...,223,petrol,2025-03-27,motokar,S60,white,W.P. Kuala Lumpur,s60,s60,S60
13498,2014,VOLVO,S60 AWD,COMPACT,2.5,5,AS6,11.6,8.3,10.1,...,232,petrol,2025-01-10,motokar,S60,silver,Perak,s60 awd,s60,S60
13499,2014,VOLVO,S60 AWD,COMPACT,2.5,5,AS6,11.6,8.3,10.1,...,232,petrol,2025-03-27,motokar,S60,white,W.P. Kuala Lumpur,s60 awd,s60,S60
13500,2014,VOLVO,S60 AWD,COMPACT,3.0,6,AS6,13.2,9.5,11.5,...,264,petrol,2025-01-10,motokar,S60,silver,Perak,s60 awd,s60,S60
13501,2014,VOLVO,S60 AWD,COMPACT,3.0,6,AS6,13.2,9.5,11.5,...,264,petrol,2025-03-27,motokar,S60,white,W.P. Kuala Lumpur,s60 awd,s60,S60

In [28]:
df_combine['fuel_type'].value_counts()

fuel_type
petrol           13444
hybrid_petrol       58
Name: count, dtype: int64

In [29]:
# Drop unnecessary columns
df_combine.drop(['MODEL_x_norm', 'MODEL_y_norm', 'MODEL_MATCHED', 'MODEL_y'], axis=1, inplace=True)
df_combine

,MODELYEAR,MAKER,MODEL_x,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,fuel_type,date_reg,type,colour,state
0,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,12.7,9.1,11.1,25,255,petrol,2025-02-03,motokar_pelbagai_utiliti,white,W.P. Kuala Lumpur
1,2014,ASTON-MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,17.4,11.3,14.7,19,338,petrol,2025-01-07,motokar,orange,W.P. Kuala Lumpur
2,2014,ASTON-MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,18.1,12.2,15.4,18,354,petrol,2025-01-07,motokar,orange,W.P. Kuala Lumpur
3,2014,ASTON-MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,17.4,11.3,14.7,19,338,petrol,2025-01-07,motokar,orange,W.P. Kuala Lumpur
4,2014,ASTON-MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,M6,18.1,12.2,15.4,18,354,petrol,2025-01-07,motokar,orange,W.P. Kuala Lumpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13497,2014,VOLVO,S60,COMPACT,2.5,5,AS6,11.3,7.8,9.7,29,223,petrol,2025-03-27,motokar,white,W.P. Kuala Lumpur
13498,2014,VOLVO,S60 AWD,COMPACT,2.5,5,AS6,11.6,8.3,10.1,28,232,petrol,2025-01-10,motokar,silver,Perak
13499,2014,VOLVO,S60 AWD,COMPACT,2.5,5,AS6,11.6,8.3,10.1,28,232,petrol,2025-03-27,motokar,white,W.P. Kuala Lumpur
13500,2014,VOLVO,S60 AWD,COMPACT,3.0,6,AS6,13.2,9.5,11.5,25,264,petrol,2025-01-10,motokar,silver,Perak
13501,2014,VOLVO,S60 AWD,COMPACT,3.0,6,AS6,13.2,9.5,11.5,25,264,petrol,2025-03-27,motokar,white,W.P. Kuala Lumpur

In [30]:
# Rename columns
df_combine.rename(columns={'MODEL_x': 'MODEL', 'fuel_type':'FUEL_TYPE', 'date_reg':'DATE_REG', 'type':'TYPE', 'colour':'COLOUR', 'state':'STATE' }, inplace=True)
df_combine
# Capital all uncapitalized letters
df_combine['FUEL_TYPE'] = df_combine['FUEL_TYPE'].str.upper()
df_combine['TYPE'] = df_combine['TYPE'].str.upper()
df_combine['COLOUR'] = df_combine['COLOUR'].str.upper()
df_combine['STATE'] = df_combine['STATE'].str.upper()
df_combine

,MODELYEAR,MAKER,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,FUEL_TYPE,DATE_REG,TYPE,COLOUR,STATE
0,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,12.7,9.1,11.1,25,255,PETROL,2025-02-03,MOTOKAR_PELBAGAI_UTILITI,WHITE,W.P. KUALA LUMPUR
1,2014,ASTON-MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,17.4,11.3,14.7,19,338,PETROL,2025-01-07,MOTOKAR,ORANGE,W.P. KUALA LUMPUR
2,2014,ASTON-MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,18.1,12.2,15.4,18,354,PETROL,2025-01-07,MOTOKAR,ORANGE,W.P. KUALA LUMPUR
3,2014,ASTON-MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,17.4,11.3,14.7,19,338,PETROL,2025-01-07,MOTOKAR,ORANGE,W.P. KUALA LUMPUR
4,2014,ASTON-MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,M6,18.1,12.2,15.4,18,354,PETROL,2025-01-07,MOTOKAR,ORANGE,W.P. KUALA LUMPUR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13497,2014,VOLVO,S60,COMPACT,2.5,5,AS6,11.3,7.8,9.7,29,223,PETROL,2025-03-27,MOTOKAR,WHITE,W.P. KUALA LUMPUR
13498,2014,VOLVO,S60 AWD,COMPACT,2.5,5,AS6,11.6,8.3,10.1,28,232,PETROL,2025-01-10,MOTOKAR,SILVER,PERAK
13499,2014,VOLVO,S60 AWD,COMPACT,2.5,5,AS6,11.6,8.3,10.1,28,232,PETROL,2025-03-27,MOTOKAR,WHITE,W.P. KUALA LUMPUR
13500,2014,VOLVO,S60 AWD,COMPACT,3.0,6,AS6,13.2,9.5,11.5,25,264,PETROL,2025-01-10,MOTOKAR,SILVER,PERAK
13501,2014,VOLVO,S60 AWD,COMPACT,3.0,6,AS6,13.2,9.5,11.5,25,264,PETROL,2025-03-27,MOTOKAR,WHITE,W.P. KUALA LUMPUR

In [ ]:
# Do the Mutli-indexing
df_combine.set_index(['MAKER', 'MODEL'], inplace=True)
df_combine

                           MODELYEAR VEHICLECLASS  ENGINESIZE  CYLINDERS  \
MAKER        MODEL
ACURA        MDX 4WD            2014  SUV - SMALL         3.5          6
ASTON-MARTIN V8 VANTAGE         2014   TWO-SEATER         4.7          8
             V8 VANTAGE         2014   TWO-SEATER         4.7          8
             V8 VANTAGE S       2014   TWO-SEATER         4.7          8
             V8 VANTAGE S       2014   TWO-SEATER         4.7          8
...                              ...          ...         ...        ...
VOLVO        S60                2014      COMPACT         2.5          5
             S60 AWD            2014      COMPACT         2.5          5
             S60 AWD            2014      COMPACT         2.5          5
             S60 AWD            2014      COMPACT         3.0          6
             S60 AWD            2014      COMPACT         3.0          6

                          TRANSMISSION  FUELCONSUMPTION_CITY  \
MAKER        MODEL
ACURA        MDX 4WD               AS6                  12.7
ASTON-MARTIN V8 VANTAGE            AM7                  17.4
             V8 VANTAGE             M6                  18.1
             V8 VANTAGE S          AM7                  17.4
             V8 VANTAGE S           M6                  18.1
...                                ...                   ...
VOLVO        S60                   AS6                  11.3
             S60 AWD               AS6                  11.6
             S60 AWD               AS6                  11.6
             S60 AWD               AS6                  13.2
             S60 AWD               AS6                  13.2

                           FUELCONSUMPTION_HWY  FUELCONSUMPTION_COMB  \
MAKER        MODEL
ACURA        MDX 4WD                       9.1                  11.1
ASTON-MARTIN V8 VANTAGE                   11.3                  14.7
             V8 VANTAGE                   12.2                  15.4
             V8 VANTAGE S                 11.3                  14.7
             V8 VANTAGE S                 12.2                  15.4
...                                        ...                   ...
VOLVO        S60                           7.8                   9.7
             S60 AWD                       8.3                  10.1
             S60 AWD                       8.3                  10.1
             S60 AWD                       9.5                  11.5
             S60 AWD                       9.5                  11.5

                           FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS FUEL_TYPE  \
MAKER        MODEL
ACURA        MDX 4WD                             25           255    PETROL
ASTON-MARTIN V8 VANTAGE                          19           338    PETROL
             V8 VANTAGE                          18           354    PETROL
             V8 VANTAGE S                        19           338    PETROL
             V8 VANTAGE S                        18           354    PETROL
...                                             ...           ...       ...
VOLVO        S60                                 29           223    PETROL
             S60 AWD                             28           232    PETROL
             S60 AWD                             28           232    PETROL
             S60 AWD                             25           264    PETROL
             S60 AWD                             25           264    PETROL

                             DATE_REG                      TYPE  COLOUR  \
MAKER        MODEL
ACURA        MDX 4WD       2025-02-03  MOTOKAR_PELBAGAI_UTILITI   WHITE
ASTON-MARTIN V8 VANTAGE    2025-01-07                   MOTOKAR  ORANGE
             V8 VANTAGE    2025-01-07                   MOTOKAR  ORANGE
             V8 VANTAGE S  2025-01-07                   MOTOKAR  ORANGE
             V8 VANTAGE S  2025-01-07                   MOTOKAR  ORANGE
...                               ...                       ...     ...
VOLVO        S60           2025-03-27                   MOTOKAR   WHITE
             S60 AWD       2025-01-10                   MOTOKAR  SILVER
             S60 AWD       2025-03-27                   MOTOKAR   WHITE
             S60 AWD       2025-01-10                   MOTOKAR  SILVER
             S60 AWD       2025-03-27                   MOTOKAR   WHITE

                                       STATE
MAKER        MODEL
ACURA        MDX 4WD       W.P. KUALA LUMPUR
ASTON-MARTIN V8 VANTAGE    W.P. KUALA LUMPUR
             V8 VANTAGE    W.P. KUALA LUMPUR
             V8 VANTAGE S  W.P. KUALA LUMPUR
             V8 VANTAGE S  W.P. KUALA LUMPUR
...                                      ...
VOLVO        S60           W.P. KUALA LUMPUR
             S60 AWD                   PERAK
             S60 AWD       W.P. KUALA LUMPUR
             S60 AWD                   PERAK
             S60 AWD       W.P. KUALA LUMPUR

[13502 rows x 15 columns]

In [32]:
df_combine.to_csv('cleaned.csv')

<h2><u>Conclusion</u></h2>

In conclusion, this project unites two similar datasets cars_2025 and FuelConsumption to analyze vehicle features and registration data on fuel consumption and carbon emissions in the 2025 car market. An exhaustive exercise in data cleaning and preparation involving duplicate removal, null value handling, column normalization, and data mapping enabled the successful merger of the datasets to allow for meaningful and accurate analysis. This integration enables the exploration of key research questions around emission patterns by make, model, and fuel type, offering valuable insights into environmental impact and trends within vehicle registrations and specifications.